DROP TABLE COMMENT;
DROP TABLE POST;

CREATE TABLE POST (
POST_ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
TEXT VARCHAR2(255) DEFAULT NULL,
PRIMARY KEY (POST_ID));

CREATE TABLE COMMENT (
COMMENT_ID NUMBER (10, 0) NOT NULL AUTO_INCREMENT,
POST_ID NUMBER (10, 0) NOT NULL,
TEXT VARCHAR2(255) DEFAULT NULL,
PRIMARY KEY(COMMENT_ID),
FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID));

INSERT INTO POST (TEXT) VALUES ('Hello world!');
INSERT INTO POST (TEXT) VALUES ('Hello.. mars?');

INSERT INTO COMMENT (POST_ID, TEXT) VALUES (1, 'Hello to you too!');
INSERT INTO COMMENT (POST_ID, TEXT) VALUES (2, 'h e l l o h u m a n');
INSERT INTO COMMENT (POST_ID, TEXT) VALUES (2, '..|..|');

DROP SEQUENCE hibernate_sequence;
CREATE SEQUENCE hibernate_sequence;