DROP TABLE COMMENT;
DROP TABLE POST;
DROP TABLE FUNCTION;
DROP TABLE USER;

CREATE TABLE USER (
  USER_ID NUMBER(10, 0) NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR2(60) NOT NULL,
  HASHED_PW VARCHAR2(60) NOT NULL,
  EMAIL VARCHAR2(100) DEFAULT NULL,
  ACTIVE BIT NOT NULL DEFAULT TRUE,
  PRIMARY KEY (USER_ID));

CREATE TABLE ROLE (
  ROLE_ID NUMBER(10, 0) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR2(100) NOT NULL,
  PRIMARY KEY(ROLE_ID));

CREATE TABLE FUNCTION (
  FUNCTION_ID NUMBER(10, 0) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR2(100) NOT NULL,
  PRIMARY KEY(FUNCTION_ID));

CREATE TABLE ROLE_FUNCTION (
  ROLE_ID NUMBER(10, 0) NOT NULL,
  FUNCTION_ID NUMBER(10, 0) NOT NULL,
  PRIMARY KEY(ROLE_ID, FUNCTION_ID),
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID),
  FOREIGN KEY (FUNCTION_ID) REFERENCES FUNCTION (FUNCTION_ID));

CREATE TABLE USER_ROLE (
  USER_ID NUMBER(10, 0) NOT NULL,
  ROLE_ID NUMBER(10, 0) NOT NULL,
  PRIMARY KEY(USER_ID, ROLE_ID),
  FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID));

CREATE TABLE POST (
  POST_ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  TEXT VARCHAR2(255) DEFAULT NULL,
  PRIMARY KEY (POST_ID));

CREATE TABLE COMMENT (
  COMMENT_ID NUMBER (10, 0) NOT NULL AUTO_INCREMENT,
  POST_ID NUMBER (10, 0) NOT NULL,
  TEXT VARCHAR2(255) DEFAULT NULL,
  PRIMARY KEY(COMMENT_ID),
  FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID));

INSERT INTO POST (TEXT) VALUES ('Hello world!');
INSERT INTO POST (TEXT) VALUES ('Hello.. mars?');

INSERT INTO COMMENT (POST_ID, TEXT) VALUES (1, 'Hello to you too!');
INSERT INTO COMMENT (POST_ID, TEXT) VALUES (2, 'h e l l o h u m a n');
INSERT INTO COMMENT (POST_ID, TEXT) VALUES (2, '..|..|');

DROP SEQUENCE hibernate_sequence;
CREATE SEQUENCE hibernate_sequence;